name: Go Test

runs:
  using: "composite"

  steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: test/go.mod
        cache-dependency-path: test/go.sum

    - name: go test
      run: |
        cd test/
        go test
      shell: bash
